#include "ch.h"
#include "hal.h"
#include "audio_io.h"

void audio_io_init(void) {
    palSetPadMode(IN1_SCALE_PORT, IN1_SCALE_PIN, PAL_MODE_OUTPUT_PUSHPULL);
    palSetPadMode(IN2_SCALE_PORT, IN2_SCALE_PIN, PAL_MODE_OUTPUT_PUSHPULL);
    palSetPadMode(OUT1_SCALE_PORT, OUT1_SCALE_PIN, PAL_MODE_OUTPUT_PUSHPULL);
    palSetPadMode(OUT2_SCALE_PORT, OUT2_SCALE_PIN, PAL_MODE_OUTPUT_PUSHPULL);

    palWritePad(IN1_SCALE_PORT, IN1_SCALE_PIN,
                IN_SCALE_LINE_LEVEL);
    palWritePad(IN2_SCALE_PORT, IN2_SCALE_PIN,
                IN_SCALE_LINE_LEVEL);
    palWritePad(OUT1_SCALE_PORT, OUT1_SCALE_PIN,
                OUT_SCALE_LINE_LEVEL);
    palWritePad(OUT2_SCALE_PORT, OUT2_SCALE_PIN,
                OUT_SCALE_LINE_LEVEL);

    palSetPadMode(IN1_MODE_PORT, IN1_MODE_PIN, PAL_MODE_OUTPUT_PUSHPULL);
    palSetPadMode(IN2_MODE_PORT, IN2_MODE_PIN, PAL_MODE_OUTPUT_PUSHPULL);
    palWritePad(IN1_MODE_PORT, IN1_MODE_PIN,
                IN1_MODE_MONO);
    palWritePad(IN2_MODE_PORT, IN2_MODE_PIN,
                IN2_MODE_MONO);

    palSetPadMode(OUT2_STR_EN_PORT, OUT2_STR_EN_PIN, PAL_MODE_OUTPUT_PUSHPULL);
    palWritePad(OUT2_STR_EN_PORT, OUT2_STR_EN_PIN,
                OUT2_STR_DISABLED);

    palSetPadMode(OUT1_BAL_EN_PORT, OUT1_BAL_EN_PIN, PAL_MODE_OUTPUT_PUSHPULL);
    palWritePad(OUT1_BAL_EN_PORT, OUT1_BAL_EN_PIN,
                BAL_ENABLED);
    palSetPadMode(OUT2_BAL_EN_PORT, OUT2_BAL_EN_PIN, PAL_MODE_OUTPUT_PUSHPULL);
    palWritePad(OUT2_BAL_EN_PORT, OUT2_BAL_EN_PIN,
                BAL_ENABLED);

    palSetPadMode(IN1_BIAS_SEL_PORT, IN1_BIAS_SEL_PIN, PAL_MODE_OUTPUT_PUSHPULL);
    palWritePad(IN1_BIAS_SEL_PORT, IN1_BIAS_SEL_PIN,
                BIAS_BIPOLAR);
    palSetPadMode(IN2_BIAS_SEL_PORT, IN2_BIAS_SEL_PIN, PAL_MODE_OUTPUT_PUSHPULL);
    palWritePad(IN2_BIAS_SEL_PORT, IN2_BIAS_SEL_PIN,
                BIAS_BIPOLAR);
    palSetPadMode(OUT1_BIAS_SEL_PORT, OUT1_BIAS_SEL_PIN, PAL_MODE_OUTPUT_PUSHPULL);
    palWritePad(OUT1_BIAS_SEL_PORT, OUT1_BIAS_SEL_PIN,
                BIAS_BIPOLAR);
    palSetPadMode(OUT2_BIAS_SEL_PORT, OUT2_BIAS_SEL_PIN, PAL_MODE_OUTPUT_PUSHPULL);
    palWritePad(OUT2_BIAS_SEL_PORT, OUT2_BIAS_SEL_PIN,
                BIAS_BIPOLAR);
}
