#ifndef __AUDIO_IO_H
#define __AUDIO_IO_H

#define IN1_SCALE_PORT GPIOH
#define IN1_SCALE_PIN 9

#define IN1_MODE_PORT GPIOI
#define IN1_MODE_PIN 10

#define IN1_BIAS_SEL_PORT GPIOC
#define IN1_BIAS_SEL_PIN 13

#define IN2_SCALE_PORT GPIOI
#define IN2_SCALE_PIN 7

#define IN2_MODE_PORT GPIOI
#define IN2_MODE_PIN 9

#define IN2_BIAS_SEL_PORT GPIOI
#define IN2_BIAS_SEL_PIN 8

#define OUT1_SCALE_PORT GPIOD
#define OUT1_SCALE_PIN 5

#define OUT1_BAL_EN_PORT GPIOD
#define OUT1_BAL_EN_PIN 4

#define OUT1_BIAS_SEL_PORT GPIOC
#define OUT1_BIAS_SEL_PIN 15

#define OUT2_STR_EN_PORT GPIOG
#define OUT2_STR_EN_PIN 3

#define OUT2_BAL_EN_PORT GPIOH
#define OUT2_BAL_EN_PIN 13

#define OUT2_SCALE_PORT GPIOH
#define OUT2_SCALE_PIN 10

#define OUT2_BIAS_SEL_PORT GPIOC
#define OUT2_BIAS_SEL_PIN 14


#define IN_SCALE_LINE_LEVEL PAL_LOW
#define IN_SCALE_CV PAL_HIGH

#define OUT_SCALE_LINE_LEVEL PAL_HIGH
#define OUT_SCALE_CV PAL_LOW

#define IN1_MODE_AUX PAL_LOW
#define IN1_MODE_MONO PAL_HIGH

#define IN2_MODE_STR PAL_LOW
#define IN2_MODE_MONO PAL_HIGH

#define BAL_ENABLED PAL_LOW
#define BAL_DISABLED PAL_HIGH

#define OUT2_STR_ENABLED PAL_LOW
#define OUT2_STR_DISABLED PAL_HIGH

#define BIAS_BIPOLAR PAL_LOW
#define BIAS_UNIPOLAR PAL_HIGH

void audio_io_init(void);

#endif
